### ISSUE TITLE
additional driver variable to update

### ISSUE THREAD

**Issue by scoward-r7** [MooseDojo/Cobbler#1]
first off, congrats on publishing!! :+1:

your `README.md` mentions changing the driver variable on line 5, but line 30 also needs to be mentioned:

https://github.com/MooseDojo/Cobbler/blob/1aaa70d3db61f900306e385b86195a78245e6217/Cobbler.rb#L30

one solution would be to make this variable based on user input / command line options.

**Comment by scampbell-r7** [comment]
I updated the readme to include line 30. Later on I may change the code to use a cli option, but I doubt it because I'm trying to keep usage as simple as possible to eliminate the requirement to provide cli options. Thanks for your feedback!
